# Server Port
server.port=8081

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Show SQL statements in the console for debugging
spring.jpa.show-sql=true

# Allow access to the H2 console in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# RabbitMQ Connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

logging.file.name=application.log
logging.level.root=INFO
